# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='moniker',
            new_name='owner',
        ),
    ]
