# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170911_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventInvitations',
            new_name='Guest',
        ),
    ]
