# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 00:58
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('size', models.PositiveSmallIntegerField(blank=True, choices=[('', '-- select --'), (1, '2-10 people'), (2, '11-50 people'), (3, '51-100 people'), (4, '101-250 people'), (5, '251 people or more')])),
                ('telephone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='Street Address')),
                ('address2', models.CharField(blank=True, max_length=128, verbose_name='Street Address 2')),
                ('municipality', models.CharField(blank=True, max_length=128, verbose_name='Municipality')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('banner_photo', models.ImageField(blank=True, upload_to='')),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
            ],
            bases=(models.Model, core.models.CreatedModifiedMixin),
        ),
    ]
