# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='municipality',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', '-- select --'), (1, '2-10 people'), (2, '11-50 people'), (3, '51-100 people'), (4, '101-250 people'), (5, '251 people or more')], null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telephone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
