# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20170912_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='join_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
