# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20170117_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='banner_photo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='profile_photo',
        ),
    ]
