# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationmembers_organizationprofiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembers',
            new_name='OrganizationMember',
        ),
        migrations.RenameModel(
            old_name='OrganizationProfiles',
            new_name='OrganizationProfile',
        ),
    ]
