# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170524_1248'),
        ('organizations', '0006_auto_20170524_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrganizationMembers_added', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(blank=True, default='member', max_length=16),
        ),
    ]
