# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20170524_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='involvement',
            field=models.IntegerField(default=0),
        ),
    ]
