# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20170907_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='title',
            new_name='name',
        ),
    ]
