# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0002_auto_20170912_1546'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taskassignee', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_taskassignee', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='person',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due',
            new_name='due_date',
        ),
        migrations.DeleteModel(
            name='TaskAssignees',
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
