# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170920_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignee',
            name='completed',
        ),
    ]
