# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_assignee_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
