# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_assignee_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='person',
            field=models.ForeignKey(blank=True, default=57, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignee',
            name='task',
            field=models.ForeignKey(blank=True, default=57, on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='tasks.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
