# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 16:17
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=32, null=True)),
                ('number_of_children', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(models.Model, core.models.CreatedModifiedMixin),
        ),
    ]
