# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170815_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
