# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20170815_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
