# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
    ]
