# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170524_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
