# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_account'),
        ('groups', '0003_auto_20170524_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GroupMembers_added', to='people.Person'),
        ),
    ]
