# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupmember_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='involvement',
            field=models.IntegerField(default=1),
        ),
    ]
