# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 16:17
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('member', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('join_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=(models.Model, core.models.CreatedModifiedMixin),
        ),
    ]
