# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='entity',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='owner',
            field=models.CharField(default='organization:1', max_length=64),
            preserve_default=False,
        ),
    ]
