# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20170907_1232'),
        ('people', '0005_auto_20170815_2058'),
        ('members', '0004_auto_20170906_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
            preserve_default=False,
        ),
    ]
